# Generated by Django 5.2.8 on 2025-11-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_symptoms_alter_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='symptoms',
            new_name='Reason',
        ),
    ]
