# Generated by Django 5.2.8 on 2025-11-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_symptoms_appointment_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Reason',
            new_name='reason',
        ),
    ]
